language: objective-c
osx_image: xcode7.3

before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- carthage update --platform iOS
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -project PrediKit.xcodeproj -scheme "PrediKit iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
  - xcodebuild -project PrediKit.xcodeproj -scheme "PrediKit OSX" ONLY_ACTIVE_ARCH=YES test | xcpretty -c
