language: objective-c
osx_image: xcode7.3

env:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
    - gem install xcpretty -N
    - gem install slather --no-ri --no-rdoc
script:
    - set -o pipefail
    - xcodebuild -project PrediKit.xcodeproj -scheme "PrediKit-iOS" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=YES test | xcpretty -c
    - xcodebuild -project PrediKit.xcodeproj -scheme "PrediKit-OSX" ONLY_ACTIVE_ARCH=YES test | xcpretty -c
    - pod lib lint --quick
after_success:
    - slather
